"""Feature extraction utilities for ScamShield."""

from pathlib import Path

from joblib import dump, load
from sklearn.feature_extraction.text import TfidfVectorizer

from .preprocessing import clean_text


class FeatureExtractor:
    """Wraps a TF-IDF vectorizer used by ScamShield text models."""

    def __init__(self):
        """Initialize the TF-IDF vectorizer with ScamShield defaults.

        Uses clean_text preprocessing and extracts 1-3 gram text features.
        """
        self.vectorizer = TfidfVectorizer(
            preprocessor=clean_text,
            ngram_range=(1, 3),
            max_features=8000,
            stop_words="english",
        )

    def fit(self, texts):
        """Fit the vectorizer vocabulary and IDF weights on input texts.

        Args:
            texts: Iterable of raw text strings.

        Returns:
            scipy.sparse matrix generated by fit_transform on the input texts.
        """
        return self.vectorizer.fit_transform(texts)

    def transform(self, texts):
        """Transform input texts into a sparse TF-IDF feature matrix.

        Args:
            texts: Iterable of raw text strings.

        Returns:
            scipy.sparse matrix of TF-IDF features.
        """
        return self.vectorizer.transform(texts)

    def save(self, path):
        """Persist the fitted vectorizer to disk.

        Args:
            path: Destination file path for serialized vectorizer.
        """
        dump(self.vectorizer, Path(path))

    @classmethod
    def load(cls, path):
        """Load a serialized vectorizer and return a configured extractor.

        Args:
            path: File path to a serialized vectorizer artifact.

        Returns:
            FeatureExtractor instance containing the loaded vectorizer.
        """
        extractor = cls()
        extractor.vectorizer = load(Path(path))
        return extractor


def get_vectorizer():
    """Return a raw vectorizer object for backward compatibility.

    Existing training code expects get_vectorizer() to return an sklearn
    vectorizer with fit_transform/transform methods.
    """
    return FeatureExtractor().vectorizer